#!/usr/bin/env bash
# Load functions and variables
. /usr/bin/common
# Display ssh logo
ssh_logo

cat << "EOF"
Connect your iDevice to this computer

The keyboard layout is in American Qwerty.
Your iDevice's default password is alpine (should automatically be entered).
Your iDevice's users are `root` and `mobile`.
Your iDevice's default port is 22.

EOF
prompt 'User: ' user
prompt 'Port: ' port

clear

blue_echo 'SSHing into your iDevice...'
DROPBEAR_PASSWORD='alpine' dbclient -J "netcat $port"  $user@iPhone || \
    failed_echo 'Failed to SSH into your iDevice.'
enter_to_quit
